FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn whitenoise

COPY . .

RUN python manage.py collectstatic --noinput

EXPOSE 7860

CMD ["gunicorn", "--bind", "0.0.0.0:7860", "maintenance_api.wsgi:application"]
